### ISSUE TITLE
Добавить в payload запроса от dialogflower к dialogflow с пользовательскими данными Яндекса

### ISSUE THREAD

**Issue by SerafimPikalov** [just-ai/dialogflower#1]
Сейчас Dialogflower возвращает пустой payload. Из-за этого нельзя сделать через меахнизм fullfilment кастомную логику под отдельного пользователя. Хотелось бы получить хотя бы блок user (и user_id) и session.application.application_id.

На примере:
Вот так выглядит payload от dialogflower: 
'originalDetectIntentRequest': {'payload': {}}, 'session': 'projects/<<SESSION>>'}

А вот как выглядит при подключенной в dialogflow интеграции с Telegram payload от Telegram:
'originalDetectIntentRequest': {'source': 'telegram', 'payload': {'data': {'message_id': 631.0, 'text': 'что почитать', 'date': 1607952282.0, 'from': {'username': '<<USERNAME>>', 'id': <<ID>>, 'first_name': '<<FIRSTNAME>>', 'language_code': 'ru', 'last_name': '<<LASTNAME>>'}, 'chat': {'id': '<<CHATID>>', 'type': 'private'}}}}, 'session': '<<SESSION>>'}

Хотелось бы чего нибудь похожего

<<___>> -так обозначены места куда подставляются id, убраны чтобы не светить персональные данные

**Comment by morfeusys** [comment]
@SerafimPikalov попробуйте - [теперь должно прилетать](https://github.com/just-ai/dialogflower#%D0%BE%D1%80%D0%B8%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81-%D0%BE%D1%82-%D0%B0%D0%BB%D0%B8%D1%81%D1%8B) как вы и описали
